### ISSUE TITLE
Помилка uncaught typeerror: illegal offset type

### ISSUE THREAD

**Issue by Pashych** [OkayCMS/OkayCMS#159]
Помилка **uncaught typeerror: illegal offset type** при відкриванні розділу _**Властивості**_ в адмінці.

У файлі backend/Helpers/BackendFeedbacksHelper.php потрібно замінити рядок 412 
з $productsCounts[$f]['translit'][] = $value->translit;
на $productsCounts[$featureId]['translit'][] = $value->translit;

Напевно описка при оптимізації коду, чи можливо щось інакше?

Версія OkayCMS 4.3, версія php 8.0,

**Comment by OkayCMS** [comment]
Виправлено у https://github.com/OkayCMS/OkayCMS/pull/152
