### ISSUE TITLE
Помилка на сторінці товару при видаленні категорії

### ISSUE THREAD

**Issue by 3anglepro** [OkayCMS/OkayCMS#217]
### Опис

Якщо видалити категорію, до якої був прив'язаний товар, на сторінку товару неможливо зайти.

### Відтворення

Найпростіший спосіб:
1. Заходимо в Каталог - Категорії 
`/backend/index.php?controller=CategoriesAdmin`
2. Обрати всі категорії - Видалити
3. Відкриваєм головну - переходимо на будь-який товар наприклад з "Хіти продажу"

### Опис помилки

`Fatal error: Uncaught TypeError: Argument 2 passed to Okay\Helpers\MetadataHelpers\ProductMetadataHelper::setUp() must be an object or null, bool given, called in /home/xgxpmqzh/wp5.3angle.pro/Okay/Controllers/ProductController.php on line 111 and defined in /home/xgxpmqzh/wp5.3angle.pro/Okay/Helpers/MetadataHelpers/ProductMetadataHelper.php:20 Stack trace: #0 /home/xgxpmqzh/wp5.3angle.pro/Okay/Controllers/ProductController.php(111): Okay\Helpers\MetadataHelpers\ProductMetadataHelper->setUp(Object(stdClass), false, Object(stdClass)) #1 [internal function]: Okay\Controllers\ProductController->render(Object(Okay\Entities\ProductsEntity), Object(Okay\Entities\BrandsEntity), Object(Okay\Entities\CategoriesEntity), Object(Okay\Helpers\ProductsHelper), Object(Okay\Entities\BlogEntity), Object(Okay\Helpers\BlogHelper), Object(Okay\Helpers\CommentsHelper), Object(Okay\Helpers\RelatedProductsHelper), Object(Okay\Helpers\MetadataHelpers\ProductMetadataHelper), Object(Okay\Core\BrowsedProducts), 'fitness-treker-...', '') #2 /home/xg in /home/xgxpmqzh/wp5.3angle.pro/Okay/Helpers/MetadataHelpers/ProductMetadataHelper.php on line 20`

### Версія

OkayCMS 4.3.0

**Comment by OkayCMS** [comment]
Fix https://github.com/OkayCMS/OkayCMS/commit/99568fab273fad644645a6c1086c3aef392330a8
