### ISSUE TITLE
Немає можливості змінити статус замовлення, якщо на складі 0 кількість

### ISSUE THREAD

**Issue by zuzul** [OkayCMS/OkayCMS#222]
### Опис

Якщо оформити замовлення на товар для якого в адмінці вказано кількість **0** (передзамовлення), блокується можливість змінити статус замовлення в адмінці.

Якщо в адмінці видалити число в полі "К-сть", тобто вказати - "**Є в наявності**" - все спрацює як слід.

### Відтворення

1. Заходимо в Налаштування сайту / Налаштування каталогу / **Вмикаємо — "Передзамовлення відсутніх товарів"**.
2. Заходимо в Каталог / Товари / Ставимо "К-сть" = **0** на обраний товар.
3. Імітуємо оформлення замовлення через кошик на сайті на обраний товар.
4. Заходимо в Замовлення / Список замовлень / відкриваємо замовлення та пробуємо змінити статус.

### Спостережена поведінка

В списку статусів замовлення активний тільки пункт **"Видалити"**.

### Очікувана поведінка

Повинні бути активними всі інші статуси.

### Оточення

Версія OkayCMS 4.3.1

**Comment by OkayCMS** [comment]
Але якщо товару нема в наявності, і його переводити в статус, який списує кількість, то будуть мінусові значення залишків товарів на складах. Це не гарно.
