### ISSUE TITLE
Додати окреме переведення поля з вартістю доставки якщо включений режим - "Оплачується окремо"

### ISSUE THREAD

**Issue by zuzul** [OkayCMS/OkayCMS#223]
## Запит функціоналу

Додати окремий переклад поля зі вартістю доставки якщо у Способі доставки включений режим - "Оплачується окремо".

### Опис

Потрібно змінити фразу **"Доставка: безкоштовно"**, що відображається в кошику, якщо в налаштуваннях включений пункт **"Оплачується окремо"**.

### Навіщо це потрібно?

Оплачується окремо - означає, що доставка **НЕ ​​безкоштовна!** Зараз якщо в адмінці включений цей пункт – у кошику пишеться: **"Доставка: безкоштовно"** – що абсолютно не правильно!

### Пропоноване рішення(я)

Якщо увімкнено пункт налаштувань **"Оплачується окремо"** - у кошику має відображатися фраза: **"Доставка: за рахунок покупця"**.

Цей напис має бути мультимовним, тому для нього потрібно додати окремий переклад.

### Оточення

Версія OkayCMS 4.3.1

**Comment by OkayCMS** [comment]
Мовна змінна для такої логіки існує і успішно функціонує: $lang['cart_paid_separate'] = 'Сплачується окремо';

За функціональною особливістю роботи бізнес логіки доставок в кошику обов'язково необхідно вказати розмір вартості безкоштовної доставки від, а точніше цей розмір не повинен дорівнювати 0.
Залишаючи поле "Безкоштовна доставка від" рівним 0 ви говорите системі, що безкоштовна доставка починається від вартості кошика в 0 грн.
Наприклад, у полі "Безкоштовна доставка від" можна вказати якусь велику величину 999999.
Якщо, наприклад, це поле заповнено коректно, тоді у доставки наприклад виводиться: Доставка (100,00 грн, Оплачується окремо). І над підсумковою вартістю кошика теж є текст: Доставка (Оплачується окремо): 100,00 грн
