### ISSUE TITLE
Немає можливості додати товари з нульовим залишком до існуючих замовлень

### ISSUE THREAD

**Issue by zuzul** [OkayCMS/OkayCMS#224]
### Опис

Якщо в адмінці для товару вказано кількість **0** (передзамовлення), цей товар не підтягується і не шукається у меню, що випадає - **"Оберіть товар, аби додати його"**.

Якщо в адмінці видалити число в полі "К-сть", тобто вказати - "**Є в наявності**" - все спрацює як слід.

### Відтворення

1. Заходимо через Адмінку в Налаштування сайту / Налаштування каталогу / **Вмикаємо — "Передзамовлення відсутніх товарів"**.
2. Заходимо через Адмінку в Каталог / Товари / Ставимо "К-сть" = **0** на обраний товар.
3. Імітуємо оформлення замовлення через кошик на сайті.
4. Заходимо через Адмінку в Замовлення / Список замовлень / відкриваємо замовлення та пробуємо додати товар у якого к-сть = **"0"**.

### Спостережена поведінка

Якщо зайти через Адмінку у існуючє замовлення, в списку товарів для додавання відображаються тільки товари у яких к-сть = "**Є в наявності**".

### Очікувана поведінка

У існуючих замовленнях, в списку товарів для додавання мають відображатись усі товари як с к-стю = **"0"** так і з к-стю **"Є в наявності"**!

### Оточення

Версія OkayCMS 4.3.1

**Comment by OkayCMS** [comment]
Товари яких немає на складі відображатись у списку за умови, що у налаштуваннях активовано налаштування - Передзамовлення відсутніх товарів.
Виправлення цієї логіки в коміті вище https://github.com/OkayCMS/OkayCMS/pull/250
