### ISSUE TITLE
404, если менять адрес блога(списка постов)

### ISSUE THREAD

**Issue by vladimirpirkhal** [OkayCMS/OkayCMS#311]
### Описание

Краткое описание проблемы.
Если в админке→SEO→Настройки ЧПУ→Url-ы для общих разделов→Список постов вписать какие-то буквы, отличные от дефолтных all-posts, то блог(список постов) пропадает по старому адресу (https://demookay.com/all-posts) и не появляется по новому (https://demookay.com/abc).
### Шаг для воспроизведения
1. На дефолтном Окае открыть админка→SEO→Настройки ЧПУ
2. В Url-ы для общих разделов→Список постов вписать уникальный набор символов, например, abc
3. Применить
4. Пробовать найти список блогов на стороне покупателя по адресам https://demookay.com/all-posts, https://demookay.com/abc
Как воспроизвести проблему, включая пользовательский код, если нужно.

### Наблюдаемое поведение

Как проявляется проблема после выполнения вышеуказанных шагов.
По дефолтному адресу (https://demookay.com/all-posts) отображается только рамка для постов, самого списка нет.
По новому адресу (https://demookay.com/abc) отдается 404
### Ожидаемое поведение

Как это должно работать после выполнения вышеуказанных шагов.
По дефолтному адресу (https://demookay.com/all-posts) отдается 404.
По новому адресу (https://demookay.com/abc) отображается блог(список постов).
### Связанные issue(s)/PR(s)

Сообщите нам, если это связано с issue(s)/PR(s).

### Окружение

Версия OkayCMS, версия php, версия mysql, версия Apache/Nginx, браузер и т.п. Любая полезная информация.
OkayCMS440, PHP7.4, mysql server_version: 5.7.38.

**Comment by restrdev** [comment]
https://github.com/OkayCMS/OkayCMS/pull/381
